### PR TITLE
HBASE-28096 [hbase-thirdparty] Also relocate the proto files in proto…

### PR DESCRIPTION
**Pull request by Apache9**
…buf-java

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  1s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 14s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 42s |  master passed  |
| +1 :green_heart: |  compile  |   0m 21s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 11s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  2s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 45s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 21s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 21s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  0s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 10s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m  9s |  hbase-shaded-protobuf in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 32s |  root in the patch passed.  |
| -1 :x: |  asflicense  |   0m 10s |  The patch generated 11 ASF License warnings.  |
|  |   |   4m 53s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-103/1/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/103 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux c7b6d2372c79 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 1f87a57 |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-103/1/testReport/ |
| asflicense | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-103/1/artifact/yetus-precommit-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 390 (vs. ulimit of 1000) |
| modules | C: hbase-shaded-protobuf . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-103/1/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 24s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  5s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 31s |  master passed  |
| +1 :green_heart: |  compile  |   0m 22s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 10s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  4s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 44s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 22s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 22s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 10s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 10s |  hbase-shaded-protobuf in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 31s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m  9s |  The patch does not generate ASF License warnings.  |
|  |   |   3m 55s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-103/2/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/103 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux e8d1aef9915f 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 1f87a57 |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-103/2/testReport/ |
| Max. process+thread count | 408 (vs. ulimit of 1000) |
| modules | C: hbase-shaded-protobuf . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-103/2/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by ndimiduk — APPROVED** [review]
This change looks fine to me, but I think the overall structure of this module is odd. We should be unpacking and generating into `${project.build.directory}/generated-sources` ; unpack the java sources into `${project.build.directory}/generated-sources/java` and the protobufs into `${project.build.directory}/generated-sources/proto`. We may have to add these additional paths to [`compileSourceRoots`](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#compileSourceRoots). Then we won't have to add all the special treatments to `src/main` in this module.

**Comment by ndimiduk** [comment]
Yep, a separate ticket is fine by me. Thanks @Apache9 .

**Pull request merged**
