### PR TITLE
HBASE-28492 [hbase-thirdparty] Bump dependency versions before releasing

### PR DESCRIPTION
**Pull request by Apache9**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 30s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 17s |  root in master failed.  |
| -1 :x: |  compile  |   0m 18s |  root in master failed.  |
| -1 :x: |  javadoc  |   0m 17s |  root in master failed.  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 18s |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 17s |  root in the patch failed.  |
| -1 :x: |  javac  |   0m 18s |  root in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   0m 18s |  root in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 18s |  root in the patch failed.  |
| +0 :ok: |  asflicense  |   0m 17s |  ASF License check generated no output?  |
|  |   |   4m 14s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/1/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/115 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux 07fe80665c68 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 726f60d |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
| mvninstall | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/1/artifact/yetus-precommit-check/output/branch-mvninstall-root.txt |
| compile | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/1/artifact/yetus-precommit-check/output/branch-compile-root.txt |
| javadoc | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/1/artifact/yetus-precommit-check/output/branch-javadoc-root.txt |
| mvninstall | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/1/artifact/yetus-precommit-check/output/patch-mvninstall-root.txt |
| compile | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/1/artifact/yetus-precommit-check/output/patch-compile-root.txt |
| javac | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/1/artifact/yetus-precommit-check/output/patch-compile-root.txt |
| javadoc | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/1/artifact/yetus-precommit-check/output/patch-javadoc-root.txt |
| unit | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/1/artifact/yetus-precommit-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/1/testReport/ |
| Max. process+thread count | 27 (vs. ulimit of 1000) |
| modules | C: . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/1/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 34s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 17s |  root in master failed.  |
| -1 :x: |  compile  |   0m 17s |  root in master failed.  |
| -1 :x: |  javadoc  |   0m 17s |  root in master failed.  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 17s |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 17s |  root in the patch failed.  |
| -1 :x: |  javac  |   0m 17s |  root in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  0s |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   0m 17s |  root in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 17s |  root in the patch failed.  |
| +0 :ok: |  asflicense  |   0m 17s |  ASF License check generated no output?  |
|  |   |   3m 18s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/2/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/115 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux a5767681b302 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 726f60d |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
| mvninstall | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/2/artifact/yetus-precommit-check/output/branch-mvninstall-root.txt |
| compile | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/2/artifact/yetus-precommit-check/output/branch-compile-root.txt |
| javadoc | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/2/artifact/yetus-precommit-check/output/branch-javadoc-root.txt |
| mvninstall | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/2/artifact/yetus-precommit-check/output/patch-mvninstall-root.txt |
| compile | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/2/artifact/yetus-precommit-check/output/patch-compile-root.txt |
| javac | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/2/artifact/yetus-precommit-check/output/patch-compile-root.txt |
| javadoc | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/2/artifact/yetus-precommit-check/output/patch-javadoc-root.txt |
| unit | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/2/artifact/yetus-precommit-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/2/testReport/ |
| Max. process+thread count | 9 (vs. ulimit of 1000) |
| modules | C: . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/2/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/3/console in case of problems.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 17s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  hadolint  |   0m  0s |  hadolint was not available.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| -1 :x: |  pre-patch  |   0m  0s |  JAVA_HOME is not defined.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/3/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/115 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs javac javadoc unit xml compile |
| uname | Linux fbd9a7cdf083 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 726f60d |
| Console output | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/3/console |
| versions | git=2.34.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/4/console in case of problems.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 37s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +0 :ok: |  hadolint  |   0m  1s |  hadolint was not available.  |
| +0 :ok: |  shelldocs  |   0m  1s |  Shelldocs was not available.  |
| -1 :x: |  pre-patch  |   0m  0s |  JAVA_HOME is not defined.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/4/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/115 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs javac javadoc unit xml compile |
| uname | Linux 5cf0e5ff86a6 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 726f60d |
| Console output | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/4/console |
| versions | git=2.34.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 12s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 47s |  master passed  |
| +1 :green_heart: |  compile  |   0m 14s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m  7s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 38s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 13s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 13s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m  6s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 34s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m  6s |  The patch does not generate ASF License warnings.  |
|  |   |   4m  7s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.45 ServerAPI=1.45 base: https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/5/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/115 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux 6a4d751086df 5.4.0-172-generic #190-Ubuntu SMP Fri Feb 2 23:24:22 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 0b6e052 |
| Default Java | Temurin-1.8.0_402-b06 |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/5/testReport/ |
| Max. process+thread count | 406 (vs. ulimit of 1000) |
| modules | C: . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-115/5/console |
| versions | git=2.34.1 maven=3.9.6 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by ndimiduk — APPROVED** [review]

**Comment by ndimiduk** [comment]
FYI @bbeaudreault

**Pull request merged**
