### PR TITLE
HBASE-26781 [hbase-thirdparty] Introduce the sun.misc.Signal delegati…

### PR DESCRIPTION
**Pull request by Apache9**
…on in hbase-unsafe

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 18s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  3s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 28s |  master passed  |
| +1 :green_heart: |  compile  |   0m 11s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m  8s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 10s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  3s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 13s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 12s |  the patch passed  |
| -1 :x: |  javac  |   0m  6s |  hbase-unsafe generated 4 new + 4 unchanged - 0 fixed = 8 total (was 4)  |
| +1 :green_heart: |  checkstyle  |   0m  8s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 10s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 21s |  hbase-noop-htrace in the patch failed.  |
| +1 :green_heart: |  unit  |   0m  7s |  hbase-unsafe in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m  9s |  The patch does not generate ASF License warnings.  |
|  |   |   3m 58s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | hbase.htrace_noop.TestHBaseTestingUtilityWithHTraceNoop |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-79/2/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/79 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile spotbugs findbugs checkstyle |
| uname | Linux 75b1a86adebb 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 9f5c6e2 |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
| javac | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-79/2/artifact/yetus-precommit-check/output/diff-compile-javac-hbase-unsafe.txt |
| unit | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-79/2/artifact/yetus-precommit-check/output/patch-unit-hbase-noop-htrace.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-79/2/testReport/ |
| Max. process+thread count | 233 (vs. ulimit of 1000) |
| modules | C: hbase-noop-htrace hbase-unsafe U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-79/2/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 48s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  spotbugs  |   0m  0s |  spotbugs executables are not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 38s |  master passed  |
| +1 :green_heart: |  compile  |   0m 10s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m  8s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 11s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  3s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 11s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 10s |  the patch passed  |
| -1 :x: |  javac  |   0m  5s |  hbase-unsafe generated 4 new + 4 unchanged - 0 fixed = 8 total (was 4)  |
| +1 :green_heart: |  checkstyle  |   0m  6s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m  9s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 27s |  hbase-noop-htrace in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  6s |  hbase-unsafe in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m  9s |  The patch does not generate ASF License warnings.  |
|  |   |   3m 44s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-79/3/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/79 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile spotbugs findbugs checkstyle |
| uname | Linux fc9c9eef9754 5.4.0-1047-aws #49~18.04.1-Ubuntu SMP Wed Apr 28 23:08:58 UTC 2021 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 9f5c6e2 |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
| javac | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-79/3/artifact/yetus-precommit-check/output/diff-compile-javac-hbase-unsafe.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-79/3/testReport/ |
| Max. process+thread count | 389 (vs. ulimit of 1000) |
| modules | C: hbase-noop-htrace hbase-unsafe U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-79/3/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
The javac failure is expected. We reference sun.misc.Signal.

**Comment by GeorryHuang** [comment]
+1

**Review by GeorryHuang — APPROVED** [review]

**Pull request merged**
