### PR TITLE
HBASE-24820 [hbase-thirdparty] Add jersey-hk2 when shading jersey and…

### PR DESCRIPTION
**Pull request by Apache9**
… bump jetty to 9.4.31

### CODE REVIEW

**Comment by Apache9** [comment]
Finally I could get all the UTs under hbase-http to pass with the shaded jetty and jersey.

There are still two problems:

1. Shaded plugin can not deal with some string literals.

https://github.com/eclipse/jetty.project/blob/450ba27947e13e66baa8cd1ce7e85a4461cacc1d/jetty-webapp/src/main/java/org/eclipse/jetty/webapp/WebAppContext.java#L137

The elements of WebAppContext.__dftServerClasses have '-' at the beginning and the shade plugin will not relocate them and cause trouble(although when shading source they are relocated...).

I do not know how to replace string literals in a class file, so the solution is to write a method in the hbase code base to do the replacement...

2. The behavior of HttpServletResponse.sendError has been changed. In the past jetty will append the error message in the status line but in jetty 9.4 it will not, and cause the TestProxyUserSpnegoHttpServer.testProxyDisallowedForUnprivileged to fail.
Seems introduced by this commit
https://github.com/eclipse/jetty.project/commit/bde86467f4e5df595773ab11ed5e80c615b741f3#diff-03fcd9b9e322e2bb4fdb46f2bbea27b3

Not sure if it is intenional or not... But anyway this could also be solved by changing the test, not a big deal.

**Comment by petersomogyi** [comment]
Can you try to add the following relocation rule to deal with `-` prefix?
```
<relocation>
  <pattern>-org.eclipse</pattern>
  <shadedPattern>-${shaded.prefix}.org.eclipse</shadedPattern>
</relocation>
```

>Not sure if it is intenional or not... But anyway this could also be solved by changing the test, not a big deal.

Changing the test looks fine to me.

**Comment by Apache9** [comment]
> Can you try to add the following relocation rule to deal with `-` prefix?
> 
> ```
> <relocation>
>   <pattern>-org.eclipse</pattern>
>   <shadedPattern>-${shaded.prefix}.org.eclipse</shadedPattern>
> </relocation>
> ```

You're right, I'm testing exactly what you suggest here(but with org.eclipse.jetty) before you post this comment :)

It is not easy to view the string literals in class file so let me depend on it in hbase to see if it works.

**Comment by Apache9** [comment]
Good, it works! I mean relocating '-org.eclipse.jetty'.

Pushed a new commit to add the relocation rule. PTAL @petersomogyi

**Pull request merged**
