### PR TITLE
HBASE-26593 [hbase-thirdparty] Set version as 4.0.1 in prep for first RC

### PR DESCRIPTION
**Pull request by Apache9**

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 38s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 23s |  Maven dependency ordering for branch  |
| -1 :x: |  mvninstall  |   0m  9s |  root in master failed.  |
| -1 :x: |  compile  |   0m 17s |  hbase-shaded-protobuf in master failed.  |
| -1 :x: |  compile  |   0m 17s |  hbase-shaded-netty in master failed.  |
| -1 :x: |  compile  |   0m 17s |  hbase-shaded-gson in master failed.  |
| -1 :x: |  compile  |   0m 17s |  hbase-shaded-miscellaneous in master failed.  |
| -1 :x: |  compile  |   0m 18s |  hbase-shaded-jetty in master failed.  |
| -1 :x: |  compile  |   0m 17s |  hbase-shaded-jersey in master failed.  |
| -1 :x: |  compile  |   0m 17s |  hbase-shaded-jackson-jaxrs-json-provider in master failed.  |
| -1 :x: |  compile  |   0m 17s |  hbase-noop-htrace in master failed.  |
| -1 :x: |  compile  |   0m 17s |  root in master failed.  |
| -1 :x: |  javadoc  |   0m 17s |  hbase-shaded-protobuf in master failed.  |
| -1 :x: |  javadoc  |   0m 17s |  hbase-shaded-netty in master failed.  |
| -1 :x: |  javadoc  |   0m 17s |  hbase-shaded-jersey in master failed.  |
| -1 :x: |  javadoc  |   0m 17s |  hbase-shaded-jackson-jaxrs-json-provider in master failed.  |
| -1 :x: |  javadoc  |   0m 17s |  hbase-noop-htrace in master failed.  |
| -1 :x: |  javadoc  |   0m 17s |  root in master failed.  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 17s |  root in master failed.  |
| +0 :ok: |  mvndep  |   0m 48s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   0m 54s |  root in the patch failed.  |
| -1 :x: |  mvninstall  |   0m 18s |  hbase-noop-htrace in the patch failed.  |
| -1 :x: |  mvninstall  |   0m 18s |  hbase-shaded-gson in the patch failed.  |
| -1 :x: |  mvninstall  |   0m 19s |  hbase-shaded-jackson-jaxrs-json-provider in the patch failed.  |
| -1 :x: |  mvninstall  |   0m 18s |  hbase-shaded-jersey in the patch failed.  |
| -1 :x: |  mvninstall  |   0m 21s |  hbase-shaded-jetty in the patch failed.  |
| -1 :x: |  mvninstall  |   0m 18s |  hbase-shaded-miscellaneous in the patch failed.  |
| -1 :x: |  mvninstall  |   0m 17s |  hbase-shaded-protobuf in the patch failed.  |
| -1 :x: |  compile  |   0m 18s |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 18s |  hbase-noop-htrace in the patch failed.  |
| -1 :x: |  compile  |   0m 17s |  hbase-shaded-gson in the patch failed.  |
| -1 :x: |  compile  |   0m 18s |  hbase-shaded-jackson-jaxrs-json-provider in the patch failed.  |
| -1 :x: |  compile  |   0m 21s |  hbase-shaded-jersey in the patch failed.  |
| -1 :x: |  compile  |   0m  5s |  hbase-shaded-jetty in the patch failed.  |
| -1 :x: |  compile  |   0m 18s |  hbase-shaded-miscellaneous in the patch failed.  |
| -1 :x: |  compile  |   0m 17s |  hbase-shaded-netty in the patch failed.  |
| -1 :x: |  compile  |   0m 18s |  hbase-shaded-protobuf in the patch failed.  |
| -1 :x: |  javac  |   0m 18s |  root in the patch failed.  |
| -1 :x: |  javac  |   0m 18s |  hbase-noop-htrace in the patch failed.  |
| -1 :x: |  javac  |   0m 17s |  hbase-shaded-gson in the patch failed.  |
| -1 :x: |  javac  |   0m 18s |  hbase-shaded-jackson-jaxrs-json-provider in the patch failed.  |
| -1 :x: |  javac  |   0m 21s |  hbase-shaded-jersey in the patch failed.  |
| -1 :x: |  javac  |   0m  5s |  hbase-shaded-jetty in the patch failed.  |
| -1 :x: |  javac  |   0m 18s |  hbase-shaded-miscellaneous in the patch failed.  |
| -1 :x: |  javac  |   0m 17s |  hbase-shaded-netty in the patch failed.  |
| -1 :x: |  javac  |   0m 18s |  hbase-shaded-protobuf in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  9s |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   0m 18s |  root in the patch failed.  |
| -1 :x: |  javadoc  |   0m 17s |  hbase-noop-htrace in the patch failed.  |
| -1 :x: |  javadoc  |   0m 18s |  hbase-shaded-gson in the patch failed.  |
| -1 :x: |  javadoc  |   0m 18s |  hbase-shaded-jackson-jaxrs-json-provider in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 16s |  root in the patch failed.  |
| -1 :x: |  unit  |   0m 17s |  hbase-noop-htrace in the patch failed.  |
| -1 :x: |  unit  |   0m 18s |  hbase-shaded-gson in the patch failed.  |
| -1 :x: |  unit  |   0m 17s |  hbase-shaded-jackson-jaxrs-json-provider in the patch failed.  |
| +1 :green_heart: |  unit  |   0m  9s |  hbase-shaded-jersey in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  6s |  hbase-shaded-jetty in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  6s |  hbase-shaded-miscellaneous in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  7s |  hbase-shaded-netty in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 12s |  hbase-shaded-protobuf in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  2s |  The patch does not generate ASF License warnings.  |
|  |   |  21m 14s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/71 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux 9ee1b85158ac 5.4.0-1054-aws #57~18.04.1-Ubuntu SMP Thu Jul 15 03:21:36 UTC 2021 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 775a3bc |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
| mvninstall | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/branch-compile-hbase-shaded-protobuf.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/branch-compile-hbase-shaded-netty.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/branch-compile-hbase-shaded-gson.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/branch-compile-hbase-shaded-miscellaneous.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/branch-compile-hbase-shaded-jetty.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/branch-compile-hbase-shaded-jersey.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/branch-compile-hbase-shaded-jackson-jaxrs-json-provider.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/branch-compile-hbase-noop-htrace.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/branch-compile-root.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/branch-javadoc-hbase-shaded-protobuf.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/branch-javadoc-hbase-shaded-netty.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/branch-javadoc-hbase-shaded-jersey.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/branch-javadoc-hbase-shaded-jackson-jaxrs-json-provider.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/branch-javadoc-hbase-noop-htrace.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/branch-javadoc-root.txt |
| mvninstall | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/branch-mvninstall-root.txt |
| mvninstall | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-mvninstall-root.txt |
| mvninstall | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-mvninstall-hbase-noop-htrace.txt |
| mvninstall | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-mvninstall-hbase-shaded-gson.txt |
| mvninstall | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-mvninstall-hbase-shaded-jackson-jaxrs-json-provider.txt |
| mvninstall | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-mvninstall-hbase-shaded-jersey.txt |
| mvninstall | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-mvninstall-hbase-shaded-jetty.txt |
| mvninstall | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-mvninstall-hbase-shaded-miscellaneous.txt |
| mvninstall | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-mvninstall-hbase-shaded-protobuf.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-compile-root.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-compile-hbase-noop-htrace.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-compile-hbase-shaded-gson.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-compile-hbase-shaded-jackson-jaxrs-json-provider.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-compile-hbase-shaded-jersey.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-compile-hbase-shaded-jetty.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-compile-hbase-shaded-miscellaneous.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-compile-hbase-shaded-netty.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-compile-hbase-shaded-protobuf.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-compile-root.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-compile-hbase-noop-htrace.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-compile-hbase-shaded-gson.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-compile-hbase-shaded-jackson-jaxrs-json-provider.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-compile-hbase-shaded-jersey.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-compile-hbase-shaded-jetty.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-compile-hbase-shaded-miscellaneous.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-compile-hbase-shaded-netty.txt |
| javac | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-compile-hbase-shaded-protobuf.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-javadoc-root.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-javadoc-hbase-noop-htrace.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-javadoc-hbase-shaded-gson.txt |
| javadoc | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-javadoc-hbase-shaded-jackson-jaxrs-json-provider.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-unit-root.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-unit-hbase-noop-htrace.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-unit-hbase-shaded-gson.txt |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/artifact/yetus-precommit-check/output/patch-unit-hbase-shaded-jackson-jaxrs-json-provider.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/testReport/ |
| Max. process+thread count | 39 (vs. ulimit of 1000) |
| modules | C: . hbase-noop-htrace hbase-shaded-gson hbase-shaded-jackson-jaxrs-json-provider hbase-shaded-jersey hbase-shaded-jetty hbase-shaded-miscellaneous hbase-shaded-netty hbase-shaded-protobuf U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/1/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by mymeiyi — APPROVED** [review]

**Comment by Apache9** [comment]
Ah, let me check the failures...

**Comment by Apache9** [comment]
Seems an env problem, can not create new thread.

Let me kick a new run.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 41s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 38s |  master passed  |
| +1 :green_heart: |  compile  |   0m 55s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 41s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 24s |  master passed  |
| +0 :ok: |  mvndep  |   0m 29s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 32s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 55s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 55s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  6s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 40s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m  9s |  hbase-shaded-protobuf in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  5s |  hbase-shaded-netty in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-shaded-gson in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  5s |  hbase-shaded-miscellaneous in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  5s |  hbase-shaded-jetty in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-shaded-jersey in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  5s |  hbase-shaded-jackson-jaxrs-json-provider in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 27s |  hbase-noop-htrace in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 31s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 39s |  The patch does not generate ASF License warnings.  |
|  |   |   9m 43s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/2/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/71 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux d95583a43ef1 5.4.0-1025-aws #25~18.04.1-Ubuntu SMP Fri Sep 11 12:03:04 UTC 2020 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 775a3bc |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/2/testReport/ |
| Max. process+thread count | 414 (vs. ulimit of 1000) |
| modules | C: hbase-shaded-protobuf hbase-shaded-netty hbase-shaded-gson hbase-shaded-miscellaneous hbase-shaded-jetty hbase-shaded-jersey hbase-shaded-jackson-jaxrs-json-provider hbase-noop-htrace . U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-71/2/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
