### PR TITLE
HBASE-28279 [hbase-thirdparty] Bump up jetty-server, jetty-http to 9.4.53.v20231009

### PR DESCRIPTION
**Pull request by chrajeshbabu**

### CODE REVIEW

**Review by bbeaudreault — APPROVED** [review]

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 56s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 17s |  root in master failed.  |
| -1 :x: |  compile  |   0m 17s |  root in master failed.  |
| -1 :x: |  javadoc  |   0m 17s |  root in master failed.  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 18s |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 17s |  root in the patch failed.  |
| -1 :x: |  javac  |   0m 17s |  root in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   0m 17s |  root in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 18s |  root in the patch failed.  |
| +0 :ok: |  asflicense  |   0m 17s |  ASF License check generated no output?  |
|  |   |   4m 38s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/1/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/107 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux 0fc8172202f7 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 2462b19 |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
| mvninstall | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/1/artifact/yetus-precommit-check/output/branch-mvninstall-root.txt |
| compile | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/1/artifact/yetus-precommit-check/output/branch-compile-root.txt |
| javadoc | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/1/artifact/yetus-precommit-check/output/branch-javadoc-root.txt |
| mvninstall | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/1/artifact/yetus-precommit-check/output/patch-mvninstall-root.txt |
| compile | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/1/artifact/yetus-precommit-check/output/patch-compile-root.txt |
| javac | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/1/artifact/yetus-precommit-check/output/patch-compile-root.txt |
| javadoc | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/1/artifact/yetus-precommit-check/output/patch-javadoc-root.txt |
| unit | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/1/artifact/yetus-precommit-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/1/testReport/ |
| Max. process+thread count | 11 (vs. ulimit of 1000) |
| modules | C: . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/1/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by NihalJain — APPROVED** [review]

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 36s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 17s |  root in master failed.  |
| -1 :x: |  compile  |   0m 17s |  root in master failed.  |
| -1 :x: |  javadoc  |   0m 17s |  root in master failed.  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 18s |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 17s |  root in the patch failed.  |
| -1 :x: |  javac  |   0m 17s |  root in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   0m 18s |  root in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 17s |  root in the patch failed.  |
| +0 :ok: |  asflicense  |   0m 18s |  ASF License check generated no output?  |
|  |   |   3m 19s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/2/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/107 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux 6af621ff92c6 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 2462b19 |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
| mvninstall | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/2/artifact/yetus-precommit-check/output/branch-mvninstall-root.txt |
| compile | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/2/artifact/yetus-precommit-check/output/branch-compile-root.txt |
| javadoc | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/2/artifact/yetus-precommit-check/output/branch-javadoc-root.txt |
| mvninstall | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/2/artifact/yetus-precommit-check/output/patch-mvninstall-root.txt |
| compile | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/2/artifact/yetus-precommit-check/output/patch-compile-root.txt |
| javac | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/2/artifact/yetus-precommit-check/output/patch-compile-root.txt |
| javadoc | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/2/artifact/yetus-precommit-check/output/patch-javadoc-root.txt |
| unit | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/2/artifact/yetus-precommit-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/2/testReport/ |
| Max. process+thread count | 9 (vs. ulimit of 1000) |
| modules | C: . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/2/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 47s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 17s |  root in master failed.  |
| -1 :x: |  compile  |   0m 18s |  root in master failed.  |
| -1 :x: |  javadoc  |   0m 18s |  root in master failed.  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 17s |  root in the patch failed.  |
| -1 :x: |  compile  |   0m 18s |  root in the patch failed.  |
| -1 :x: |  javac  |   0m 18s |  root in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   0m 17s |  root in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 17s |  root in the patch failed.  |
| +0 :ok: |  asflicense  |   0m 17s |  ASF License check generated no output?  |
|  |   |   3m 30s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/4/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/107 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux 75bccc067c02 5.4.0-1103-aws #111~18.04.1-Ubuntu SMP Tue May 23 20:04:10 UTC 2023 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 2462b19 |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
| mvninstall | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/4/artifact/yetus-precommit-check/output/branch-mvninstall-root.txt |
| compile | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/4/artifact/yetus-precommit-check/output/branch-compile-root.txt |
| javadoc | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/4/artifact/yetus-precommit-check/output/branch-javadoc-root.txt |
| mvninstall | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/4/artifact/yetus-precommit-check/output/patch-mvninstall-root.txt |
| compile | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/4/artifact/yetus-precommit-check/output/patch-compile-root.txt |
| javac | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/4/artifact/yetus-precommit-check/output/patch-compile-root.txt |
| javadoc | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/4/artifact/yetus-precommit-check/output/patch-javadoc-root.txt |
| unit | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/4/artifact/yetus-precommit-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/4/testReport/ |
| Max. process+thread count | 27 (vs. ulimit of 1000) |
| modules | C: . U: . |
| Console output | https://ci-hbase.apache.org/job/HBase-Thirdparty-PreCommit/job/PR-107/4/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by chrajeshbabu** [comment]
Build passing locally. Some how the pipelines not running.

**Pull request merged**
