### PR TITLE
HBASE-25609 [hbase-thirdparty] Bump version to 4.0.0-SNAPSHOT on mast…

### PR DESCRIPTION
**Pull request by Apache9**
…er branch

### CODE REVIEW

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  6s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 33s |  master passed  |
| +1 :green_heart: |  compile  |   0m 47s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 36s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 22s |  master passed  |
| +0 :ok: |  mvndep  |   0m 27s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 40s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 56s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 56s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  6s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 38s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 12s |  hbase-shaded-protobuf in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-shaded-netty in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  6s |  hbase-shaded-gson in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-shaded-miscellaneous in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  5s |  hbase-shaded-jetty in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  6s |  hbase-shaded-jersey in the patch passed.  |
| -1 :x: |  unit  |   3m 45s |  hbase-noop-htrace in the patch failed.  |
| +1 :green_heart: |  unit  |   0m 29s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 33s |  The patch does not generate ASF License warnings.  |
|  |   |  13m  1s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-57/1/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/57 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux a60e78146de3 5.4.0-1054-aws #57~18.04.1-Ubuntu SMP Thu Jul 15 03:21:36 UTC 2021 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 247c926 |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
| unit | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-57/1/artifact/yetus-precommit-check/output/patch-unit-hbase-noop-htrace.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-57/1/testReport/ |
| Max. process+thread count | 395 (vs. ulimit of 1000) |
| modules | C: hbase-shaded-protobuf hbase-shaded-netty hbase-shaded-gson hbase-shaded-miscellaneous hbase-shaded-jetty hbase-shaded-jersey hbase-noop-htrace . U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-57/1/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 38s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 19s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   1m 18s |  master passed  |
| +1 :green_heart: |  compile  |   0m 47s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 35s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 21s |  master passed  |
| +0 :ok: |  mvndep  |   0m 26s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 18s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 47s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 47s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  5s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 34s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m  8s |  hbase-shaded-protobuf in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  5s |  hbase-shaded-netty in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-shaded-gson in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-shaded-miscellaneous in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  5s |  hbase-shaded-jetty in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-shaded-jersey in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 26s |  hbase-noop-htrace in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 29s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 33s |  The patch does not generate ASF License warnings.  |
|  |   |   9m 20s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-57/2/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/57 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux 7450045cc58b 5.4.0-1054-aws #57~18.04.1-Ubuntu SMP Thu Jul 15 03:21:36 UTC 2021 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 247c926 |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-57/2/testReport/ |
| Max. process+thread count | 414 (vs. ulimit of 1000) |
| modules | C: hbase-shaded-protobuf hbase-shaded-netty hbase-shaded-gson hbase-shaded-miscellaneous hbase-shaded-jetty hbase-shaded-jersey hbase-noop-htrace . U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-57/2/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 39s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  4s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 22s |  master passed  |
| +1 :green_heart: |  compile  |   0m 46s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 35s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 29s |  master passed  |
| +0 :ok: |  mvndep  |   0m 34s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 20s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 47s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 47s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  5s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 35s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m  9s |  hbase-shaded-protobuf in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-shaded-netty in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-shaded-gson in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  5s |  hbase-shaded-miscellaneous in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-shaded-jetty in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  5s |  hbase-shaded-jersey in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 28s |  hbase-noop-htrace in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 32s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 32s |  The patch does not generate ASF License warnings.  |
|  |   |   8m 21s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-57/3/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/57 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux 193bd53a52a2 5.4.0-1054-aws #57~18.04.1-Ubuntu SMP Thu Jul 15 03:21:36 UTC 2021 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 247c926 |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-57/3/testReport/ |
| Max. process+thread count | 411 (vs. ulimit of 1000) |
| modules | C: hbase-shaded-protobuf hbase-shaded-netty hbase-shaded-gson hbase-shaded-miscellaneous hbase-shaded-jetty hbase-shaded-jersey hbase-noop-htrace . U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-57/3/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache-HBase** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  1s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  5s |  Maven dependency ordering for branch  |
| -1 :x: |  mvninstall  |   0m 12s |  root in master failed.  |
| -1 :x: |  compile  |   0m  5s |  hbase-shaded-jetty in master failed.  |
| +1 :green_heart: |  javadoc  |   0m 41s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 25s |  master passed  |
| +0 :ok: |  mvndep  |   0m 30s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 33s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 48s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 48s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  6s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 35s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 10s |  hbase-shaded-protobuf in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-shaded-netty in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-shaded-gson in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  5s |  hbase-shaded-miscellaneous in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-shaded-jetty in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  5s |  hbase-shaded-jersey in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 25s |  hbase-noop-htrace in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 32s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 32s |  The patch does not generate ASF License warnings.  |
|  |   |   8m 59s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-57/4/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/57 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux 0baba3b14ef8 5.4.0-1054-aws #57~18.04.1-Ubuntu SMP Thu Jul 15 03:21:36 UTC 2021 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 247c926 |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
| mvninstall | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-57/4/artifact/yetus-precommit-check/output/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-57/4/artifact/yetus-precommit-check/output/branch-compile-hbase-shaded-jetty.txt |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-57/4/testReport/ |
| Max. process+thread count | 413 (vs. ulimit of 1000) |
| modules | C: hbase-shaded-protobuf hbase-shaded-netty hbase-shaded-gson hbase-shaded-miscellaneous hbase-shaded-jetty hbase-shaded-jersey hbase-noop-htrace . U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-57/4/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by nyl3532016 — APPROVED** [review]

**Comment by Apache-HBase** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 38s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -0 :warning: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  4s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   0m 21s |  master passed  |
| +1 :green_heart: |  compile  |   0m 46s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 34s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 25s |  master passed  |
| +0 :ok: |  mvndep  |   0m 29s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 18s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 47s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 47s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  5s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m 35s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m  9s |  hbase-shaded-protobuf in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  5s |  hbase-shaded-netty in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-shaded-gson in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-shaded-miscellaneous in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  5s |  hbase-shaded-jetty in the patch passed.  |
| +1 :green_heart: |  unit  |   0m  4s |  hbase-shaded-jersey in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 29s |  hbase-noop-htrace in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 30s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 32s |  The patch does not generate ASF License warnings.  |
|  |   |   8m 12s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-57/5/artifact/yetus-precommit-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/hbase-thirdparty/pull/57 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux ee5dff33bec9 5.4.0-1054-aws #57~18.04.1-Ubuntu SMP Thu Jul 15 03:21:36 UTC 2021 x86_64 GNU/Linux |
| Build tool | maven |
| git revision | master / 247c926 |
| Default Java | Oracle Corporation-1.8.0_282-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-57/5/testReport/ |
| Max. process+thread count | 416 (vs. ulimit of 1000) |
| modules | C: hbase-shaded-protobuf hbase-shaded-netty hbase-shaded-gson hbase-shaded-miscellaneous hbase-shaded-jetty hbase-shaded-jersey hbase-noop-htrace . U: . |
| Console output | https://ci-hadoop.apache.org/job/HBase/job/HBase-Thirdparty-PreCommit/job/PR-57/5/console |
| versions | git=2.20.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Apache9** [comment]
OK, good. Finally we got a clean run...

Let me merge...

**Pull request merged**
